apiVersion: apps/v1
kind: Deployment
metadata:
  name: vertical-spread-go
  namespace: vertical-spread-staging
  labels:
    app: vertical-spread-go
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vertical-spread-go
  template:
    metadata:
      labels:
        app: vertical-spread-go
    spec:
      containers:
      - name: vertical-spread-go
        image: trustdan/auto-vertical-spread-go:latest
        ports:
        - containerPort: 50051  # gRPC port
        - containerPort: 2112   # Metrics port
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
        env:
        - name: ENV
          value: "staging"
        - name: LOG_LEVEL
          value: "info"
        - name: SERVER_HOST
          value: "0.0.0.0"
        - name: SERVER_PORT
          value: "50051"
        - name: METRICS_HOST
          value: "0.0.0.0"
        - name: METRICS_PORT
          value: "2112"
        volumeMounts:
        - name: config-volume
          mountPath: /etc/scanner
      volumes:
      - name: config-volume
        configMap:
          name: vertical-spread-config
