apiVersion: v1
kind: Service
metadata:
  name: vertical-spread-python
  namespace: vertical-spread-staging
spec:
  selector:
    app: vertical-spread-python
  ports:
  - port: 8000
    targetPort: 8000
  type: ClusterIP 