// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetContainers():Promise<Array<main.ContainerInfo>>;

export function LoadConfig():Promise<main.Config>;

export function PauseContainer(arg1:string):Promise<void>;

export function PauseStack():Promise<void>;

export function ReloadConfig():Promise<void>;

export function SaveAndRestart(arg1:main.Config):Promise<void>;

export function SaveConfig(arg1:main.Config):Promise<void>;

export function SendSignal(arg1:string,arg2:string):Promise<void>;

export function Status():Promise<string>;

export function UnpauseContainer(arg1:string):Promise<void>;

export function UnpauseStack():Promise<void>;
