// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetContainers() {
  return window['go']['main']['App']['GetContainers']();
}

export function LoadConfig() {
  return window['go']['main']['App']['LoadConfig']();
}

export function PauseContainer(arg1) {
  return window['go']['main']['App']['PauseContainer'](arg1);
}

export function PauseStack() {
  return window['go']['main']['App']['PauseStack']();
}

export function ReloadConfig() {
  return window['go']['main']['App']['ReloadConfig']();
}

export function SaveAndRestart(arg1) {
  return window['go']['main']['App']['SaveAndRestart'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SendSignal(arg1, arg2) {
  return window['go']['main']['App']['SendSignal'](arg1, arg2);
}

export function Status() {
  return window['go']['main']['App']['Status']();
}

export function UnpauseContainer(arg1) {
  return window['go']['main']['App']['UnpauseContainer'](arg1);
}

export function UnpauseStack() {
  return window['go']['main']['App']['UnpauseStack']();
}
