// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckRequiredServices() {
  return window['go']['main']['App']['CheckRequiredServices']();
}

export function ClearCache(arg1) {
  return window['go']['main']['App']['ClearCache'](arg1);
}

export function ConfigureSchedule(arg1) {
  return window['go']['main']['App']['ConfigureSchedule'](arg1);
}

export function CreateBackup() {
  return window['go']['main']['App']['CreateBackup']();
}

export function DeployStack() {
  return window['go']['main']['App']['DeployStack']();
}

export function GetContainers() {
  return window['go']['main']['App']['GetContainers']();
}

export function ListBackups() {
  return window['go']['main']['App']['ListBackups']();
}

export function LoadConfig() {
  return window['go']['main']['App']['LoadConfig']();
}

export function PauseContainer(arg1) {
  return window['go']['main']['App']['PauseContainer'](arg1);
}

export function PauseStack() {
  return window['go']['main']['App']['PauseStack']();
}

export function ReloadConfig() {
  return window['go']['main']['App']['ReloadConfig']();
}

export function RestoreBackup(arg1) {
  return window['go']['main']['App']['RestoreBackup'](arg1);
}

export function SaveAndRestart(arg1) {
  return window['go']['main']['App']['SaveAndRestart'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SendSignal(arg1, arg2) {
  return window['go']['main']['App']['SendSignal'](arg1, arg2);
}

export function ShowStatusDialog() {
  return window['go']['main']['App']['ShowStatusDialog']();
}

export function StartupSequenceCheck() {
  return window['go']['main']['App']['StartupSequenceCheck']();
}

export function Status() {
  return window['go']['main']['App']['Status']();
}

export function TestIBKRConnection(arg1) {
  return window['go']['main']['App']['TestIBKRConnection'](arg1);
}

export function UnpauseContainer(arg1) {
  return window['go']['main']['App']['UnpauseContainer'](arg1);
}

export function UnpauseStack() {
  return window['go']['main']['App']['UnpauseStack']();
}
