// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckRequiredServices():Promise<Array<main.ServiceStatus>>;

export function ClearCache(arg1:string):Promise<void>;

export function ConfigureSchedule(arg1:main.ScheduleConfig):Promise<void>;

export function CreateBackup():Promise<string>;

export function DeployStack():Promise<void>;

export function GetContainers():Promise<Array<main.ContainerInfo>>;

export function GetVersion():Promise<string>;

export function GetVersionDetails():Promise<Record<string, string>>;

export function ListBackups():Promise<Array<string>>;

export function LoadConfig():Promise<main.Config>;

export function PauseContainer(arg1:string):Promise<void>;

export function PauseStack():Promise<void>;

export function ReloadConfig():Promise<void>;

export function RestoreBackup(arg1:string):Promise<void>;

export function SaveAndRestart(arg1:main.Config):Promise<void>;

export function SaveConfig(arg1:main.Config):Promise<void>;

export function SendSignal(arg1:string,arg2:string):Promise<void>;

export function ShowStatusDialog():Promise<void>;

export function StartupSequenceCheck():Promise<void>;

export function Status():Promise<string>;

export function TestIBKRConnection(arg1:main.IBKRConfig):Promise<main.ServiceStatus>;

export function UnpauseContainer(arg1:string):Promise<void>;

export function UnpauseStack():Promise<void>;
