repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: https://github.com/psf/black
    rev: 23.3.0  # Match your project's Black version
    hooks:
    -   id: black

-   repo: https://github.com/pycqa/isort
    rev: 5.12.0  # Match your project's isort version
    hooks:
    -   id: isort

# Optional: Add mypy type checking
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.3.0  # Match your project's mypy version
    hooks:
    -   id: mypy
        additional_dependencies: [types-requests]
