# Trading Strategies Configuration

# Strategy Parameters
HIGH_BASE_MAX_ATR_RATIO: 2.0
HIGH_BASE_MIN_RSI: 60

LOW_BASE_MIN_ATR_RATIO: 0.5
LOW_BASE_MAX_RSI: 40

BULL_PULLBACK_RSI_THRESHOLD: 45
BULL_PULLBACK_RECOVERY_PERIODS: 2
BULL_PULLBACK_UPTREND_PERIODS: 20

BEAR_RALLY_RSI_THRESHOLD: 55
BEAR_RALLY_REVERSAL_PERIODS: 2
BEAR_RALLY_DOWNTREND_PERIODS: 20

# Risk Management
RISK_PER_TRADE: 0.02  # 2% account risk per trade
MAX_POSITIONS: 5
MAX_DAILY_TRADES: 3
STOP_LOSS_ATR_MULT: 2.0
MAX_HOLDING_PERIOD: 10

# IBKR API Connection
ibkr:
  host: "127.0.0.1"
  port: 7497  # TWS: 7497, IB Gateway: 4001
  client_id: 1
  read_only: false
  account: ""  # Set your account ID or leave blank to use active account
  use_ib_insync: true  # Use new implementation instead of placeholder
  timeout: 20  # Connection timeout in seconds
  auto_reconnect: true  # Automatically try to reconnect on disconnection
  max_rate: 45  # Maximum API requests per second (IB's limit is 50)

# Backtest Parameters
INITIAL_EQUITY: 100000
BACKTEST_SYMBOLS:
  - AAPL
  - MSFT
  - GOOGL
  - AMZN
  - META
  - NFLX
  - TSLA
  - NVDA
  - AMD
  - INTC

# Scanner Configuration
USE_GO_SCANNER: false
GO_SCANNER_HOST: localhost
GO_SCANNER_PORT: 50051
SCAN_SYMBOLS:
  - AAPL
  - MSFT
  - GOOGL
  - AMZN
  - META
  - NFLX
  - TSLA
  - NVDA
  - AMD
  - INTC

# Logging Configuration
LOGGING:
  CONSOLE:
    ENABLED: true
    LEVEL: INFO
  FILE:
    ENABLED: true
    LEVEL: DEBUG
    FILENAME: trading_log.json
    MAX_BYTES: 10485760  # 10MB
    BACKUP_COUNT: 5
