// Wails bindings for Go functions
// This is a placeholder file - in a real implementation, these would be generated by Wails

export function GetConfig() {
    return window.go.main.App.GetConfig();
}

export function UpdateConfig(config) {
    return window.go.main.App.UpdateConfig(config);
}

export function SaveConfigurationAndRestart(config) {
    return window.go.main.App.SaveConfigurationAndRestart(config);
}

export function PauseTradingServices() {
    return window.go.main.App.PauseTradingServices();
}

export function ResumeTradingServices() {
    return window.go.main.App.ResumeTradingServices();
}

export function GetLatestMetrics() {
    return window.go.main.App.GetLatestMetrics();
}

export function TestAlertNotification(channelType, message) {
    return window.go.main.App.TestAlertNotification(channelType, message);
}

export function GetStatus() {
    return window.go.main.App.GetStatus();
}

export function GetConfigSchema() {
    return window.go.main.App.GetConfigSchema();
}
