apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-orchestrator
  namespace: trading
  labels:
    app: python-orchestrator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-orchestrator
  template:
    metadata:
      labels:
        app: python-orchestrator
    spec:
      containers:
      - name: orchestrator
        image: trustdan/auto-vertical-spread-python:latest
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: config-volume
          mountPath: /config
          readOnly: true
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
      volumes:
      - name: config-volume
        persistentVolumeClaim:
          claimName: trader-config
