apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-scanner
  namespace: trading
  labels:
    app: go-scanner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-scanner
  template:
    metadata:
      labels:
        app: go-scanner
    spec:
      containers:
      - name: scanner
        image: trustdan/auto-vertical-spread-go:latest
        ports:
        - containerPort: 50051
        - containerPort: 2112
        volumeMounts:
        - name: config-volume
          mountPath: /config
          readOnly: true
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        livenessProbe:
          httpGet:
            path: /metrics
            port: 2112
          initialDelaySeconds: 30
          periodSeconds: 10
      volumes:
      - name: config-volume
        persistentVolumeClaim:
          claimName: trader-config
