// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FetchOptionChain(arg1) {
  return window['go']['main']['App']['FetchOptionChain'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetConfigSchema() {
  return window['go']['main']['App']['GetConfigSchema']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function LoadConfig() {
  return window['go']['main']['App']['LoadConfig']();
}

export function PauseStack() {
  return window['go']['main']['App']['PauseStack']();
}

export function SaveAndRestartStack(arg1) {
  return window['go']['main']['App']['SaveAndRestartStack'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function TestConnection() {
  return window['go']['main']['App']['TestConnection']();
}

export function UnpauseStack() {
  return window['go']['main']['App']['UnpauseStack']();
}
