// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetConfig():Promise<main.Config>;

export function GetConfigSchema():Promise<string>;

export function GetStatus():Promise<main.StatusInfo>;

export function Greet(arg1:string):Promise<string>;

export function LoadConfig():Promise<main.Config>;

export function PauseStack():Promise<string>;

export function SaveAndRestartStack(arg1:main.Config):Promise<string>;

export function SaveConfig(arg1:main.Config):Promise<void>;

export function TestConnection():Promise<boolean>;

export function UnpauseStack():Promise<string>;
