apiVersion: apps/v1
kind: Deployment
metadata:
  name: traderadmin-orchestrator
  namespace: traderadmin
  labels:
    app: traderadmin-orchestrator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traderadmin-orchestrator
  template:
    metadata:
      labels:
        app: traderadmin-orchestrator
    spec:
      volumes:
        - name: config-volume
          persistentVolumeClaim:
            claimName: traderadmin-config-pvc
      containers:
        - name: orchestrator
          image: traderadmin/orchestrator:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
          volumeMounts:
            - name: config-volume
              mountPath: /app/config
              readOnly: true
          env:
            - name: LOG_LEVEL
              value: "INFO"
            - name: CONFIG_PATH
              value: "/app/config/config.toml"
            - name: HEALTH_CHECK_PORT
              value: "8080"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 3
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
