// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {models} from '../models';

export function GetConfig():Promise<main.Configuration>;

export function GetConfigSchema():Promise<string>;

export function GetLatestMetrics():Promise<models.AllMetrics>;

export function GetStatus():Promise<main.StatusInfo>;

export function IsConfigLoaded():Promise<boolean>;

export function LoadConfig():Promise<void>;

export function PauseTradingServices():Promise<void>;

export function ResumeTradingServices():Promise<void>;

export function SaveConfig():Promise<void>;

export function SaveConfigurationAndRestart(arg1:Record<string, any>):Promise<void>;

export function TestAlertNotification(arg1:string,arg2:string):Promise<void>;

export function TestIBKRConnection():Promise<boolean>;

export function UpdateConfig(arg1:main.Configuration):Promise<void>;
