// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetConfigSchema() {
  return window['go']['main']['App']['GetConfigSchema']();
}

export function GetLatestMetrics() {
  return window['go']['main']['App']['GetLatestMetrics']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function IsConfigLoaded() {
  return window['go']['main']['App']['IsConfigLoaded']();
}

export function LoadConfig() {
  return window['go']['main']['App']['LoadConfig']();
}

export function PauseTradingServices() {
  return window['go']['main']['App']['PauseTradingServices']();
}

export function ResumeTradingServices() {
  return window['go']['main']['App']['ResumeTradingServices']();
}

export function SaveConfig() {
  return window['go']['main']['App']['SaveConfig']();
}

export function SaveConfigurationAndRestart(arg1) {
  return window['go']['main']['App']['SaveConfigurationAndRestart'](arg1);
}

export function TestAlertNotification(arg1, arg2) {
  return window['go']['main']['App']['TestAlertNotification'](arg1, arg2);
}

export function TestIBKRConnection() {
  return window['go']['main']['App']['TestIBKRConnection']();
}

export function UpdateConfig(arg1) {
  return window['go']['main']['App']['UpdateConfig'](arg1);
}
