apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-scanner
  labels:
    app: ibkr-trader
    component: scanner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ibkr-trader
      component: scanner
  template:
    metadata:
      labels:
        app: ibkr-trader
        component: scanner
    spec:
      containers:
      - name: scanner
        image: ibkr-trader/go-scanner:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: CONFIG_FILE
          value: "/config/config.toml"
        - name: SERVER_HOST
          value: "0.0.0.0"
        - name: SERVER_PORT
          value: "50051"
        ports:
        - containerPort: 50051
          name: grpc
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "500m"
            memory: "512Mi"
        volumeMounts:
        - name: config
          mountPath: /config
          readOnly: true
      securityContext:
        fsGroup: 2000
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: trader-config
