apiVersion: v1
kind: Service
metadata:
  name: vertical-spread-go
  namespace: vertical-spread-production
spec:
  selector:
    app: vertical-spread-go
  ports:
  - name: grpc
    port: 50051
    targetPort: 50051
  - name: metrics
    port: 2112
    targetPort: 2112
  type: ClusterIP

