[tool.poetry]
name = "ibkr-trader"
version = "0.1.0"
description = "Auto Vertical Spread Trader for IBKR"
authors = ["Your Name <your.email@example.com>"]
readme = "README.md"
packages = [{include = "src"}]

[tool.poetry.dependencies]
python = ">=3.8,<4.0"
pandas = "^2.0.0"
pandas-ta = "^0.3.14b"
grpcio = "^1.54.0"
grpcio-tools = "^1.54.0"
ib-insync = "^0.9.85"
pydantic = "^2.0.0"
requests = "^2.28.2"
pyyaml = "^6.0"
python-dotenv = "^1.0.0"

[tool.poetry.group.dev.dependencies]
pytest = "^7.3.1"
black = "^23.3.0"
mypy = "^1.3.0"
pytest-cov = "^4.1.0"
isort = "^5.12.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 88
target-version = ["py38"]

[tool.isort]
profile = "black"
line_length = 88

[tool.mypy]
python_version = "3.8"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
disallow_incomplete_defs = true 